// <auto-generated />
namespace EGuidebook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Route_CreatedByUserID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Route_CreatedByUserID));
        
        string IMigrationMetadata.Id
        {
            get { return "201710262042022_Route_CreatedByUserID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
