// <auto-generated />
namespace EGuidebook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SystemSettingsModelSMTP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SystemSettingsModelSMTP));
        
        string IMigrationMetadata.Id
        {
            get { return "201707051850231_SystemSettingsModelSMTP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
