// <auto-generated />
namespace EGuidebook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Spot_OpeningHours_Tickers_Images_CategoryID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Spot_OpeningHours_Tickers_Images_CategoryID));
        
        string IMigrationMetadata.Id
        {
            get { return "201708291415427_Spot_OpeningHours_Tickers_Images_CategoryID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
