// <auto-generated />
namespace EGuidebook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Spots_Routes_swap_column_names : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Spots_Routes_swap_column_names));
        
        string IMigrationMetadata.Id
        {
            get { return "201710292340153_Spots_Routes_swap_column_names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
